In [25]:
import pandas as pd
import numpy as np
import re
import pickle
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
from nltk.corpus import stopwords
from gensim.models import KeyedVectors, Word2Vec
from pathlib import Path
from datetime import datetime
from collections import Counter
import json
from sklearn.model_selection import GridSearchCV

In [26]:
import fsspec
import huggingface_hub
from deep_translator import GoogleTranslator

In [31]:
data_fake = pd.read_csv("data/Fake.csv")
data_true = pd.read_csv("data/True.csv")

data_fake.head(3)

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"

In [37]:
data_fake["label"]=0
data_true["label"]=1

In [ ]:
eng_data = pd.concat([data_true, data_fake], ignore_index=True)
eng_data = eng_data.sample(frac=1).reset_index(drop=True)

In [41]:
eng_data

,title,text,subject,date,label
0,Iran's Khamenei warns U.S. against 'wrong move...,DUBAI (Reuters) - Iran will not be bullied by ...,worldnews,"September 17, 2017",1
1,ESPIONAGE ACT VIOLATION? HILLARY EXPOSES Names...,America keeps waiting for word that Hillary wi...,left-news,"Jun 5, 2016",0
2,SHE’S GOT THE SCOOP! CATHERINE HERRIDGE: “Obam...,,left-news,"Mar 6, 2017",0
3,Clinton names Obama veterans to White House tr...,"WEST HARRISON, N.Y. (Reuters) - Looking to lay...",politicsNews,"August 16, 2016",1
4,Trump slams federal court ruling on funding fo...,WASHINGTON (Reuters) - President Donald Trump ...,politicsNews,"April 26, 2017",1
...,...,...,...,...,...
44893,Malaysia arrests 20 over suspected terror links,KUALA LUMPUR (Reuters) - Malaysia has arrested...,worldnews,"December 22, 2017",1
44894,Lawmakers Condemn ‘Dangerous Abuse Of Subpoen...,"Only April 28, nearly 100 lawmakers sent a let...",News,"May 1, 2016",0
44895,Trump claims Obama wiretapped him during campa...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"March 4, 2017",1
44896,“MAXINE WATERS IN A GLITTERY COWBOY HAT” Goes ...,The left is going ballistic over supposed word...,politics,"Oct 18, 2017",0
44897,Togo opposition calls for president to quit as...,LOME (Reuters) - Togo s opposition chief calle...,worldnews,"September 6, 2017",1

In [50]:
eng_data = eng_data[
    ~eng_data['subject'].isin(['politics', 'politicsNews'])
]

In [51]:
eng_data["subject"].unique()

array(['worldnews', 'left-news', 'Middle-east', 'News', 'Government News',
       'US_News'], dtype=object)

In [53]:
eng_data.drop(columns=["subject", "date"], inplace=True)

In [55]:
eng_data.to_csv('data/eng_data', index=False)